### ISSUE TITLE
lack files for evaluation

### ISSUE THREAD

**Issue by mayubo2333** [xingyaoww/code4struct#1]
Hi,

Thanks for your impressive work! When I evaluate the generation results, however, I found there might lacks some file:

1. I could not find the ace_roles.json (though I have ace_roles+hierarchy.json)
https://github.com/xingyaoww/code4struct/blob/main/src/scripts/evaluation/eval-all-ace.sh#L16

2. I could not find the src/tools/pandoc-toc-sidebar/toc-sidebar.html as well
https://github.com/xingyaoww/code4struct/blob/main/src/scripts/evaluation/eval-all-ace.sh#L21

Would you mind updating the two files in this repo? Looking forward for your help!

**Comment by InfiniH** [comment]
I'm also facing the same issue. Has anyone found a solution for this problem yet?

**Comment by InfiniH** [comment]
You can solve your problem by executing the following command.  
`python3 src/scripts/data/parse_ACE_events.py \
    --ace-roles-filepath data/ontology/ace/raw/event_role_ACE.json \
    --ace-entity-filepath data/ontology/ace/raw/event_role_entity_ACE.json \
    --base-entity-filepath data/ontology/ldc/base_entities/base_entities.json \
    --output-filepath data/ontology/ace/processed/ace_roles`

**Comment by xingyaoww** [comment]
Thanks for pointing it out! You can follow @InfiniH's instructions to generate the `ace_roles.json.` I have updated the repo to include `src/tools/pandoc-toc-sidebar`.
