### ISSUE TITLE
Hierarchy split file not found

### ISSUE THREAD

**Issue by LazyFyh** [xingyaoww/code4struct#2]
Hi,
Thanks for the open source code contribution!
When I preprocess the data on setting "Cross-sibling Transfer", I find the file "data/extraction/ace/interim/ACE05-E/hierarchy-split/train_test_hierarchy.json" can not be found.
How can I get this file? 
Thanks for your reply!

**Comment by xingyaoww** [comment]
Sorry for replying late! I have uploaded the file to the corresponding directory in this repo; please check [this commit](https://github.com/xingyaoww/code4struct/commit/26c5875845720f3cf71b40c69fdc4ad0f00550ab).

**Comment by LazyFyh** [comment]
Thx for your reply!
